<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Polar.Factograph.Domain/Polar.Factograph.Domain.csproj" />
    <ProjectReference Include="../Polar.Factograph.Fog/Polar.Factograph.Fog.csproj" />
    <ProjectReference Include="../../../../Polar.DB/src/Polar.DB.Typed/Polar.DB.Typed.csproj" />
  </ItemGroup>
</Project>
